export enum sagaCommentActions {
  FETCH_COMMENTS_SAGA = 'FETCH_COMMENTS_SAGA',
  SET_COMMENTS_SAGA = 'SET_COMMENTS_SAGA',
  DELETE_COMMENTS_SAGA = 'DELETE_COMMENTS_SAGA',
  CHANGE_COMMENTS_SAGA = 'CHANGE_COMMENTS_SAGA',
}
