export enum sagaActions {
  FETCH_COLUMNS_SAGA = 'FETCH_COLUMNS_SAGA',
  SET_COLUMN_SAGA = 'SET_COLUMN_SAGA',
  DELETE_COLUMN_SAGA = 'DELETE_COLUMN_SAGA',
  CHANGE_COLUMN_SAGA = 'CHANGE_COLUMN_SAGA',
}
