export enum sagaActions {
  FETCH_PRAYERS_SAGA = 'FETCH_PRAYERS_SAGA',
  SET_PRAYERS_SAGA = 'SET_PRAYERS_SAGA',
  DELETE_PRAYERS_SAGA = 'DELETE_PRAYERS_SAGA',
  CHANGE_PRAYERS_SAGA = 'CHANGE_PRAYERS_SAGA',
}
